
## Esri "Account Manager -- Natural Resources" Cover Letter
### Carolyn Hanrahan 
### February 13th, 2024 


------------------------------------------------------------------------------------



#### Dear Esri hiring managers, 

Thank you so much for taking the time to read through my application for your “Account Manager - Natural Resources” position. I appreciate your thoughtful consideration and time. I believe I have strong geospatial analysis skills, customer service and team management capabilities, and a robust quantitative ecology and natural resources background. I am excited at the prospect of working as part of the Esri team and contributing to “the science of where”. 

I am currently finishing my Master's degree at the University of Vermont Rubenstein School of the Environment and Natural Resources (UVM). While at UVM, I have developed my GIS skills through learning as a student, and working as a graduate teaching assistant. I have enjoyed learning about geoprocessing tools in ArcGIS pro, map layout formation, as well as utilizing additional GIS applications such as the ArcGIS Online Field Maps app for my own graduate research. While at UVM, I spent a semester working as a contractor with the Spatial Analysis Lab in collaboration with Google examining tree canopy composition in major U.S. cities. While working on this project, I further developed my GIS skills by calculating percent tree canopy from drone data and cross-referencing it with Google Earth Engine AI-generated data. This was a fulfilling and exciting project to lead. 

In addition to my GIS skills, I have extensive background working with and managing teams. Whether that be through helping lead teaching teams or working with others in my past jobs and internships, I feel confident in my ability to do this kindly and effectively. I have experience developing budgets during my time working as the Assistant Program Director at SEA and in my Wolf Ridge ELC teaching position. I have developed a deep understanding of forestry and natural resources concepts, and how they can be analyzed and visualized with GIS software. I have been described as reliable, communicative, and motivated by those I have worked with in the past. I am proficient in major communication programs and software such as Microsoft Office, and have programming experience in R, Markdown, Python, and VS Code. Most importantly, I have the ability to learn new skills quickly and am always willing to ask for and offer help to those on my team. 

Thank you so much once again for your time and consideration!

#### Sincerely, 
#### Carolyn Hanrahan 



